removert:

  # 
  isScanFileKITTIFormat: false

  # @ save option 
  saveMapPCD: true 
  saveCleanScansPCD: true
  save_pcd_directory: "/root/catkin_ws/src/lt-mapper/sessions/out/session1-session2-manyloops/removert/"

  # @ sequence info
  central_sess_scan_dir: "/root/catkin_ws/src/lt-mapper/sessions/in/session1/Scans/"
  central_sess_pose_path: "/root/catkin_ws/src/lt-mapper/sessions/out/session1-session2-manyloops/session1_central_aft_intersession_loops.txt"

  query_sess_scan_dir: "/root/catkin_ws/src/lt-mapper/sessions/in/session2/Scans/"
  query_sess_pose_path: "/root/catkin_ws/src/lt-mapper/sessions/out/session1-session2-manyloops/session2_central_aft_intersession_loops.txt"

  #
  sequence_vfov: 31 # Hesai XT-32: 360 x 31 deg, 32 canais
  sequence_hfov: 360

  # @ Sequence's BaseToLidar info
  ExtrinsicLiDARtoPoseBase: [1.0, 0.0, 0.0, 0.0, 
                             0.0, 1.0, 0.0, 0.0, 
                             0.0, 0.0, 1.0, 0.0, 
                             0.0, 0.0, 0.0, 1.0]

  # @ Sampling nodes 
  use_keyframe_gap: true 
  keyframe_gap: 1

  start_idx: 1
  end_idx: 149

  # @ auto repeat
  clean_for_all_scan: true
  batch_size: 150
  valid_ratio_to_save: 0.75

  # @ Range image resolution
  remove_resolution_list: [2.5]
  revert_resolution_list: [2.2]

  # @ Removert params 
  downsample_voxel_size: 0.05
  num_nn_points_within: 2
  dist_nn_points_within: 0.01

  # @ For faster
  num_omp_cores: 16

  # @ Para visualizacao
  rimg_color_min: 0.0
  rimg_color_max: 20.0
