build: 
	qmake-qt4 -o Makefile.qmake-qt4
	make -f Makefile.qmake-qt4

clean:
	qmake-qt4 -o Makefile.qmake-qt4
	make -f Makefile.qmake-qt4 clean

debug:
	qmake-qt4 -o Makefile.qmake-qt4
	make -f Makefile.qmake-qt4

export:

phase1:

phase2:
	qmake-qt4 -o Makefile.qmake-qt4
	make -f Makefile.qmake-qt4
