include ../../Makefile.conf

LINK = g++

MODULE_NAME = RRT Model Classes
MODULE_COMMENT =   
CFLAGS += #-pg  #-fopenmp
CXXFLAGS += #-pg #-fopenmp

SOURCES = tree.cpp rrt_node.cpp command.cpp robot_state.cpp pose.cpp global_state.cpp

include ../../Makefile.rules
