include ../../Makefile.conf

LINK = g++

MODULE_NAME = HYPERGRAPHSCLAM CUSTOM ELEMENTS
MODULE_COMMENT =

CXXFLAGS += -std=c++11 -O2

IFLAGS += -I$(CARMEN_HOME)/src/hypergraphsclam/CustomElements/ -I$(CARMEN_HOME)/src/hypergraphsclam/src/ -std=c++11 -O2

include ../../Makefile.rules
