include $(CARMEN_HOME)/src/Makefile.conf

MODULE_NAME = SEG MAP 
MODULE_COMMENT = Segmap

SUBDIRS += libsegmap gicp graphslam_fast programs # scripts examples

include $(CARMEN_HOME)/src/Makefile.rules
