include ../Makefile.conf

LFLAGS += -lglobal -lparam_interface -lipc 

CFLAGS += -std=c99 -O3

MODULE_NAME = CAR LAI
MODULE_COMMENT = Module 

SOURCES = car_lai.c
	
PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES = 
PUBLIC_BINARIES = car_lai 

TARGETS = car_lai

PUBLIC_LIBRARIES_SO = 

car_lai: car_lai.o

include ../Makefile.rules