// created by font2c; source image: etc/fonts/10x20.png
// Image Width = 950, Height = 20
// Letter size = 10 x 20
#define WW 0x00
#define o  0xff
static unsigned char font10x20[95][200] = {
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,o ,o ,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,WW,WW,
    o ,o ,WW,WW,o ,WW,WW,o ,WW,WW,
    o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,WW,WW,
    o ,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,WW,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,WW,WW,o ,
    o ,o ,o ,WW,WW,o ,o ,WW,WW,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,WW,WW,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,o ,WW,WW,o ,WW,WW,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,WW,WW,WW,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,WW,o ,
    o ,o ,o ,WW,WW,WW,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,WW,WW,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,WW,WW,WW,WW,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,WW,WW,WW,WW,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,o ,o ,o ,WW,WW,o ,o ,o ,o ,
    o ,WW,WW,WW,WW,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  },
  {
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,WW,WW,WW,o ,o ,WW,WW,o ,
    o ,WW,WW,o ,WW,WW,o ,WW,WW,o ,
    o ,WW,WW,o ,o ,WW,WW,WW,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o ,
    o ,o ,o ,o ,o ,o ,o ,o ,o ,o
  }
};
#undef WW
#undef o
