#ifndef _MAIN_H
#define _MAIN_H

#define COMVIEW_VERSION_MAJOR  1
#define COMVIEW_VERSION_MINOR  2
#define COMVIEW_VERSION_MICRO  0
#define COMVIEW_VERSION_DATE "Jul-19-00"
#define COMVIEW_COMMIT_DATE "$Date: 2000/07/19 22:06:15 $"

#endif /* _MAIN_H */
