rm bin/Touareg2.mtl
rm bin/Touareg2.obj
rm bin/can_playback
rm bin/can_playback_one_can
rm bin/can_view
rm bin/converte_video_para_whatsapp
rm bin/fake_odometry
rm bin/filetypes.sh
rm bin/final_goal_pose.txt
rm bin/ford_escape/trailer-cargo.obj
rm bin/gdown.pl
rm bin/grep_all
rm bin/log_fix_messages
rm bin/make_log
rm bin/mv_log.sh
rm bin/oa.txt
rm bin/publish_pose_from_annotation
rm bin/rddf_build_from_file
rm bin/rddf_generate.py
rm bin/rddf_resample
rm bin/rddf_view.py
rm bin/rebuild_caffe
rm bin/save_map_images
rm bin/timestamp_graph
rm bin/toyota_corolla_simulator
rm bin/update_map_from_image
rm bin/util_publish_dummy_gps
rm bin/util_publish_final_goal
rm data/gui/navigator_gui2_annotation.glade
rm src/imu_viewer/.qmake.stash

