include ../../Makefile.conf

CFLAGS += 
IFLAGS += 
LFLAGS += -lstdc++

MODULE_NAME = subdir_1
MODULE_COMMENT =   

SOURCES = subdir_1.cpp
PUBLIC_INCLUDES = subdir_1.hpp
PUBLIC_LIBRARIES = libsubdir_1.a 
PUBLIC_BINARIES = 

TARGETS = libsubdir_1.a

libsubdir_1.a: subdir_1.o

include ../../Makefile.rules
