include ../../Makefile.conf

CFLAGS += 
IFLAGS += 
LFLAGS += 

MODULE_NAME = subdir_2
MODULE_COMMENT = 

SOURCES = subdir_2.c
PUBLIC_INCLUDES = subdir_2.h
PUBLIC_LIBRARIES = libsubdir_2.a  
PUBLIC_BINARIES = 

TARGETS = libsubdir_2.a

libsubdir_2.a: subdir_2.o

include ../../Makefile.rules
