INC_DIR = ../../nn_lib
INC_CMD = -I $(INC_DIR)

all:
	g++ -Wall -o simple_neuron_vgram_classification simple_neuron_vgram_classification.cpp $(INC_CMD)
clean:
	rm -rf simple_neuron_vgram_classification
run:
	./simple_neuron_vgram_classification
