include ../../Makefile.conf

CFLAGS += 
IFLAGS += 
LFLAGS += -lipc -pthread -lglobal -lbase_ackerman_interface -lgps_xyz_interface -lparam_interface

MODULE_NAME = PUBLISH_ODOMETRY_BASED_ON_GPS
MODULE_COMMENT = Publish odometry based on GPS

SOURCES = publish_odometry_based_on_gps.c
PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES =  
PUBLIC_BINARIES = publish_odometry_based_on_gps

TARGETS = publish_odometry_based_on_gps

publish_odometry_based_on_gps: publish_odometry_based_on_gps.o 

include ../../Makefile.rules
