/* Auto-generated by genmsg_cpp for file /home/rcnascimento/ros/visual_search_thin/msg/output.msg */
#ifndef VISUAL_SEARCH_THIN_MESSAGE_OUTPUT_H
#define VISUAL_SEARCH_THIN_MESSAGE_OUTPUT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Point.h"
#include "geometry_msgs/Point.h"

namespace visual_search_thin
{
template <class ContainerAllocator>
struct output_ {
  typedef output_<ContainerAllocator> Type;

  output_()
  : header()
  , saccade_point()
  , saccade_vector()
  , measured_scale_factor(0.0)
  , measured_confidence(0.0)
  {
  }

  output_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , saccade_point(_alloc)
  , saccade_vector(_alloc)
  , measured_scale_factor(0.0)
  , measured_confidence(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _saccade_point_type;
   ::geometry_msgs::Point_<ContainerAllocator>  saccade_point;

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _saccade_vector_type;
   ::geometry_msgs::Point_<ContainerAllocator>  saccade_vector;

  typedef double _measured_scale_factor_type;
  double measured_scale_factor;

  typedef double _measured_confidence_type;
  double measured_confidence;


  typedef boost::shared_ptr< ::visual_search_thin::output_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visual_search_thin::output_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct output
typedef  ::visual_search_thin::output_<std::allocator<void> > output;

typedef boost::shared_ptr< ::visual_search_thin::output> outputPtr;
typedef boost::shared_ptr< ::visual_search_thin::output const> outputConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::visual_search_thin::output_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::visual_search_thin::output_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace visual_search_thin

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::visual_search_thin::output_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::visual_search_thin::output_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::visual_search_thin::output_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ecbde82c1c4afe878388aae3241a9e29";
  }

  static const char* value(const  ::visual_search_thin::output_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xecbde82c1c4afe87ULL;
  static const uint64_t static_value2 = 0x8388aae3241a9e29ULL;
};

template<class ContainerAllocator>
struct DataType< ::visual_search_thin::output_<ContainerAllocator> > {
  static const char* value() 
  {
    return "visual_search_thin/output";
  }

  static const char* value(const  ::visual_search_thin::output_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::visual_search_thin::output_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
#point saccade_point\n\
geometry_msgs/Point saccade_point\n\
#point saccade_vector\n\
geometry_msgs/Point saccade_vector\n\
float64 measured_scale_factor\n\
float64 measured_confidence\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::visual_search_thin::output_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::visual_search_thin::output_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::visual_search_thin::output_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::visual_search_thin::output_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.saccade_point);
    stream.next(m.saccade_vector);
    stream.next(m.measured_scale_factor);
    stream.next(m.measured_confidence);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct output_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visual_search_thin::output_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::visual_search_thin::output_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "saccade_point: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.saccade_point);
    s << indent << "saccade_vector: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.saccade_vector);
    s << indent << "measured_scale_factor: ";
    Printer<double>::stream(s, indent + "  ", v.measured_scale_factor);
    s << indent << "measured_confidence: ";
    Printer<double>::stream(s, indent + "  ", v.measured_confidence);
  }
};


} // namespace message_operations
} // namespace ros

#endif // VISUAL_SEARCH_THIN_MESSAGE_OUTPUT_H

