include ../Makefile.conf


MODULE_NAME = IMU
MODULE_COMMENT = Generic IMU interface

SOURCES =

PUBLIC_INCLUDES = imu_messages.h imu_interface.h
PUBLIC_LIBRARIES = libimu_interface.a
PUBLIC_BINARIES = 

TARGETS = libimu_interface.a 


libimu_interface.a: imu_interface.o


include  ../Makefile.rules

