include ../../Makefile.conf

LINK = g++

MODULE_NAME = HyperGraphSlam Messages
MODULE_COMMENT =

IFLAGS += -I$(CARMEN_HOME)/src/hypergraphslam/Helpers/ -I$(CARMEN_HOME)/src/hypergraphslam/Messages/

#cheating
IFLAGS += -std=c++11 -O3

include ../../Makefile.rules
