include $(CARMEN_HOME)/src/Makefile.conf

MODULE_NAME = SENSORS
MODULE_COMMENT = Drivers of different sensors

SUBDIRS += camera ultrasonic web_cam kinect minoru ouster laser_new

# #####################################3
# Deprecated:
# #####################################3
# SUBDIRS += laser_old 

include $(CARMEN_HOME)/src/Makefile.rules
