
/*
 * Structure:        pxvidformat
 * Copyright:        (C) EPIX, Inc. 2000-2008
 * Created:        Fri Nov 13 09:47:11 2009
 * By:                EPIX(r)  XCAP V3.0
 * OS:                Linux 64 bit
 */
struct pxvidformat pxvidformat_561_id31232 =
{
    1988,                                                   /* ddch.len       */
    561,                                                    /* ddch.mos       */
    0,                                                      /* ddch.id        */
    0,                                                      /* ddch.op        */
    0,                                                      /* ddch.un        */
    0,                                                      /* ddch.rw        */
    0,                                                      /* ddch.fu        */
    0,                                                      /* ddch.rs        */
    30819,                                                  /* fgfamily       */
    23,                                                     /* fgmodel        */
    7183,                                                   /* fgsubmodel     */
    0,                                                      /* fgcustomid     */
    2005,   4,      1,                                      /* fgdefdate      */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* fgcamera */
    0,                                                      /* fgsignature    */
    99,     0,      1,      134256640,                      /* fgcamdope      */
    4,      1920,   0,      4,                              /* xviddim        */
    4,      1920,   0,      4,                              /* xdatdim        */
    1,      1080,   0,      0,                              /* yviddim        */
    1,      1080,   0,      0,                              /* ydatdim        */
    0,      1920,   0,      2,                              /* xvidoffset     */
    0,      1080,   0,      2,                              /* yvidoffset     */
    0,      0,      0,      0,                              /* xvidoffdim     */
    0,      0,      0,      0,                              /* yvidoffdim     */
    1,      1,      0,      0,                              /* datfields      */
    1,      1,      0,      0,                              /* datchannels    */
    1,      1,      0,      0,                              /* datphylds      */
    0,      0,      0,      0,                              /* rsvd2          */
    1,      1,      1,      0,                              /* vidylaces      */
    1,      1,      1,      0,                              /* vidchannels    */
    0,      0,      0,      0,      0,      0,      0,      0,       /* inputmuxs */
    0,      0,      0,      0,      0,      0,      0,      0,       /* outputmuxs */
    0,      0,      0,      0,      0,      0,      0,      0,       /* splitscreens */
    2,      0,      0,      0,      0,      0,      0,      0,       /* syncsources */
    31232,  25088,  0,      0,      0,      0,      0,      0,       /* videomodes */
    1,      0,      0,      0,      0,      0,      0,      0,       /* fieldmods */
    1,      2147483647,     0,      0,                      /* buffers        */
    1,      1,      1,      0,                              /* vidxlaces      */
    0,      0,      0,      0,                              /* rsvd3          */
    0,                                                      /* as.hoffset     */
    0,                                                      /* as.voffset     */
    0,                                                      /* as.fieldsperframe */
    0,                                                      /* as.pixelsperclock */
    0,                                                      /* as.pixiesperclock */
    0,                                                      /* as.linesperframe */
    0,                                                      /* as.pixelsperline */
    0,      0,                                              /* as.pixelclkfreq */
    0,      0,                                              /* as.vperiod     */
    0,      0,                                              /* as.hperiod     */
    30,     1,                                              /* as.framerate   */
    0,                                                      /* as.fieldperiodicity */
    0,                                                      /* as.lineperiodicity */
    0,                                                      /* as.hscanorder  */
    0,                                                      /* as.vscanorder  */
    0,                                                      /* as.framespertrigger */
    0,                                                      /* as.scanclass   */
    0,                                                      /* as.phyldsperframe */
    0,      0,      0,      0,      0,      0,      0,       /* as.rsvd4      */
    32,                                                     /* is.hoffset     */
    9,                                                      /* is.voffset     */
    1,                                                      /* is.fieldsperframe */
    2,                                                      /* is.pixelsperclock */
    0,                                                      /* is.pixiesperclock */
    0,                                                      /* is.linesperframe */
    0,                                                      /* is.pixelsperline */
    50000,  1000,                                           /* is.pixelclkfreq */
    333333, 10000000,                                       /* is.vperiod     */
    308,    10000000,                                       /* is.hperiod     */
    300000300,      10000000,                               /* is.framerate   */
    1,                                                      /* is.fieldperiodicity */
    1,                                                      /* is.lineperiodicity */
    108,                                                    /* is.hscanorder  */
    116,                                                    /* is.vscanorder  */
    1,                                                      /* is.framespertrigger */
    2,                                                      /* is.scanclass   */
    1,                                                      /* is.phyldsperframe */
    0,      0,      0,      0,      0,      0,      0,       /* is.rsvd4      */
    6,      1,                                              /* pixelwidth     */
    6,      1,                                              /* pixelheight    */
    0,      0,                                              /* pixeldepth     */
    114,                                                    /* widthunits     */
    114,                                                    /* heightunits    */
    0,                                                      /* depthunits     */
    1,                                                      /* boardspercamera */
    0,                                                      /* linesyncupdelay */
    0,                                                      /* fieldsyncupdelay */
    0,                                                      /* framesyncupdelay */
    0,                                                      /* fieldflip      */
    1000,                                                   /* nosynctimeout  */
    0,                                                      /* phyldflip      */
    0,                                                      /* prefixdata     */
    0,                                                      /* postfixdata    */
    0,                                                      /* imagesperframe */
    0x12,                                                   /* camlinkconfig  */
    0,      0,      0,                                      /* rsvd5          */
    33,     0,      0,      0,      0,      0,      0,      0,       /* vid.pixhints */
    12,     12,     0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* vid.pixbits */
    2,      0,      0,      0,      0,      0,      0,      0,       /* vid.pixmems */
    22160,  19014,  60587,  31842,  25291,  55091,  4052,   32875,   /* vid.pixdopes */
    33,     0,      0,      0,      0,      0,      0,      0,       /* dat.pixhints */
    8,      8,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* dat.pixbits */
    1,      0,      0,      0,      0,      0,      0,      0,       /* dat.pixmems */
    55527,  13709,  35217,  39178,  4783,   41672,  26093,  14943,   /* dat.pixdopes */
    0,      0,      0,      0,      0,      0,      0,      0,       /* img.pixhints */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* img.pixbits */
    0,      0,      0,      0,      0,      0,      0,      0,       /* img.pixmems */
    18881,  54264,  8649,   11973,  33147,  25997,  9148,   60240,   /* img.pixdopes */
};

/*
 * Structure:        pxvidres
 * Copyright:        (C) EPIX, Inc. 2000-2008
 * Created:        Fri Nov 13 09:47:11 2009
 * By:                EPIX(r)  XCAP V3.0
 * OS:                Linux 64 bit
 */
struct pxvidres pxvidres_125_id31232 =
{
    496,                                                    /* ddch.len       */
    125,                                                    /* ddch.mos       */
    0,                                                      /* ddch.id        */
    0,                                                      /* ddch.op        */
    0,                                                      /* ddch.un        */
    0,                                                      /* ddch.rw        */
    0,                                                      /* ddch.fu        */
    0,                                                      /* ddch.rs        */
    1920,                                                   /* x.datsamples   */
    1920,                                                   /* x.vidsamples   */
    0,                                                      /* x.vidoffset    */
    1919,                                                   /* x.vidoffsend   */
    0,      0,      0,      0,      0,      0,      0,      0,       /* x.rsvd */
    1,                                                      /* x.setmaxdatsamples */
    1,                                                      /* x.setmaxvidsamples */
    1,                                                      /* x.setmidvidoffset */
    0,                                                      /* x.vs.on        */
    0,      0,      0,      0,      0,      0,      0,      0,       /* x.vs.parm */
    0,                                                      /* x.sv.on        */
    0,                                                      /* x.sv.pos       */
    0,                                                      /* x.sv.spc       */
    1080,                                                   /* y.datsamples   */
    1080,                                                   /* y.vidsamples   */
    0,                                                      /* y.vidoffset    */
    1079,                                                   /* y.vidoffsend   */
    0,      0,      0,      0,      0,      0,      0,      0,       /* y.rsvd */
    1,                                                      /* y.setmaxdatsamples */
    1,                                                      /* y.setmaxvidsamples */
    1,                                                      /* y.setmidvidoffset */
    0,                                                      /* y.vs.on        */
    0,      0,      0,      0,      0,      0,      0,      0,       /* y.vs.parm */
    0,                                                      /* y.sv.on        */
    0,                                                      /* y.sv.pos       */
    0,                                                      /* y.sv.spc       */
    1,                                                      /* datfields      */
    1,                                                      /* datchannels    */
    1,                                                      /* setmaxdatfields */
    1,                                                      /* setmaxdatchannels */
    1,                                                      /* datphylds      */
    1,                                                      /* setmaxdatphylds */
    1080,   0,      1079,   0,      0,      0,              /* rsvd1          */
    1,                                                      /* vid.pixies     */
    12,     0,      0,      0,                              /* vid.pixiebits  */
    33,                                                     /* vid.pixhint    */
    2,                                                      /* vid.pixmem     */
    22160,                                                  /* vid.pixdope    */
    0,                                                      /* vid.setpixbits */
    1,                                                      /* dat.pixies     */
    8,      0,      0,      0,                              /* dat.pixiebits  */
    33,                                                     /* dat.pixhint    */
    1,                                                      /* dat.pixmem     */
    55527,                                                  /* dat.pixdope    */
    0,                                                      /* dat.setpixbits */
    3,                                                      /* img.pixies     */
    8,      8,      8,      0,                              /* img.pixiebits  */
    3,                                                      /* img.pixhint    */
    0,                                                      /* img.pixmem     */
    18881,                                                  /* img.pixdope    */
    0,                                                      /* img.setpixbits */
    1920,                                                   /* line.pd        */
    1920,                                                   /* line.pdod      */
    1920,                                                   /* line.pdodal    */
    1920,                                                   /* line.pdodalsf  */
    0,                                                      /* line.rsvd2     */
    2073600,                                                /* field.pd       */
    2073608,                                                /* field.pdod     */
    2073664,                                                /* field.pdodal   */
    2073664,                                                /* field.pdodalsf */
    0,                                                      /* field.rsvd2    */
    2073600,                                                /* frame.pd       */
    2073608,                                                /* frame.pdod     */
    2073664,                                                /* frame.pdodal   */
    2073664,                                                /* frame.pdodalsf */
    0,                                                      /* frame.rsvd2    */
    16,                                                     /* framebuffers   */
    0,                                                      /* rsvdbuffers    */
    0,      0,      0,      0,      0,      0,      0,       /* rsvd3         */
};

/*
 * Structure:        pxvidmode
 * Copyright:        (C) EPIX, Inc. 2000-2008
 * Created:        Fri Nov 13 09:47:11 2009
 * By:                EPIX(r)  XCAP V3.0
 * OS:                Linux 64 bit
 */
struct pxvidmode pxvidmode_79_id31232 =
{
    312,                                                    /* ddch.len       */
    79,                                                     /* ddch.mos       */
    0,                                                      /* ddch.id        */
    0,                                                      /* ddch.op        */
    0,                                                      /* ddch.un        */
    0,                                                      /* ddch.rw        */
    0,                                                      /* ddch.fu        */
    0,                                                      /* ddch.rs        */
    1,                                                      /* vidchannels    */
    1,                                                      /* buffer         */
    0,                                                      /* panxy.x        */
    0,                                                      /* panxy.y        */
    0,                                                      /* useimphys      */
    0,      0,      0,      0,      0,      0,      0,      0,       /* rsvd2 */
    31232,  0,      0,      0,                              /* vidmode        */
    1,      0,      0,      0,                              /* vidylace       */
    2,      0,      0,      0,                              /* syncsource     */
    0,      0,      0,      0,                              /* vidopt         */
    0,      0,      0,      0,                              /* inputmux       */
    0,      0,      0,      0,                              /* outputmux      */
    0,      0,      0,      0,                              /* splitscreen    */
    1,      0,      0,      0,                              /* fieldmod       */
    1,      0,      0,      0,                              /* vidxlace       */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,                              /* rsvd1          */
    1,                                                      /* setmaxvidylace */
    1,                                                      /* setmaxvidchannels */
    1,                                                      /* setmaxvidxlace */
    0,      0,      0,      0,      0,      0,      0,       /* rsvd3         */
};

/*
 * Structure:        pxvidphys
 * Copyright:        (C) EPIX, Inc. 2000-2008
 * Created:        Fri Nov 13 09:47:11 2009
 * By:                EPIX(r)  XCAP V3.0
 * OS:                Linux 64 bit
 */
struct pxvidphys pxvidphys_118_id31232 =
{
    664,                                                    /* ddch.len       */
    118,                                                    /* ddch.mos       */
    0,                                                      /* ddch.id        */
    0,                                                      /* ddch.op        */
    0,                                                      /* ddch.un        */
    0,                                                      /* ddch.rw        */
    0,                                                      /* ddch.fu        */
    0,                                                      /* ddch.rs        */
    46912794371520, 20,     20,     46912584528672, 46912794371520, 46912649043256, 1094957632,     47481706160361,
    9,      46912794371072, 1094957712,     47481706246206, 46912794371072, 12582962,       46912794371072, 46912854037008,
    46912855396752, 46912649043256, 46912584528672, 46912649043256, 1094189056,     46912583896832, 1094957728,     46912650908576,  /* startadrs */
    1094957816,     46912650927304, 0,      46912650908584, 0,      1094957808,     1094957888,     46912509584194,
    0,      46912583896832, 1094957824,     46912650898864, 1094957928,     46912650929960, 0,      46912650898872,
    0,      1094957920,     1094958000,     46912509583642, 1,      0,      1,      46912563501848,  /* endadrs */
    1094957936,     0,      3018107954,     10922,  1094958032,     0,      3018120392,     10922,
    0,      0,      3018107992,     10922,  0,      0,      1094958024,     0,
    1094958104,     0,      2876776730,     10922,  2930694936,     10922,  1,      0,       /* linelength */
    1,      0,      1094958040,     0,      3018079485,     10922,  1094958120,     0,
    3018084640,     10922,  3127462717,     10922,  3120743424,     10922,  1094958384,     0,
    1094958384,     0,      3120743448,     10922,  0,      0,      3138816203,     10922,   /* linestride */
    1094958160,                                             /* bufadrs        */
    841800556,                                              /* bufsize        */
    3120915808,                                             /* bufxdim        */
    10922,                                                  /* bufydim        */
    3161567072,                                             /* bufidim        */
    10922,                                                  /* bufzdim        */
    1094958192,                                             /* upatita        */
    0,                                                      /* bufjdim        */
    0,      0,      0,                                      /* rsvd           */
    1094958312,                                             /* buffer         */
    1094958448,                                             /* stateid        */
    0,                                                      /* tracker        */
};

/*
 * Structure:        pxvidimage
 * Copyright:        (C) EPIX, Inc. 2000-2008
 * Created:        Fri Nov 13 09:47:11 2009
 * By:                EPIX(r)  XCAP V3.0
 * OS:                Linux 64 bit
 */
struct pxvidimage pxvidimage_251_id31232 =
{
    996,                                                    /* ddch.len       */
    251,                                                    /* ddch.mos       */
    0,                                                      /* ddch.id        */
    0,                                                      /* ddch.op        */
    0,                                                      /* ddch.un        */
    0,                                                      /* ddch.rw        */
    0,                                                      /* ddch.fu        */
    0,                                                      /* ddch.rs        */
    0,                                                      /* mt.order       */
    0,                                                      /* mt.mode        */
    0,      0,      0,      0,                              /* mt.arg         */
    0,                                                      /* bp.order       */
    13,                                                     /* bp.mode        */
    33,     2,      0,      0,                              /* bp.arg         */
    1,                                                      /* cs.order       */
    0,                                                      /* cs.mode        */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,                              /* cs.intorgb     */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,                              /* cs.fromrgb     */
    0,                                                      /* cs.scale       */
    0,                                                      /* wb.order       */
    3,                                                      /* wb.mode        */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* wb.darkreference */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* wb.darktarget */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* wb.brightreference */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* wb.brighttarget */
    750,    750,    750,    0,      750,    750,    750,    0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* wb.gamma */
    0,                                                      /* pc.order       */
    0,                                                      /* pc.mode        */
    0,      0,      0,      0,                              /* pc.arg         */
    0,                                                      /* sc.order       */
    0,                                                      /* sc.mode        */
    0,      0,      0,      0,                              /* sc.arg         */
    0,                                                      /* rz.order       */
    0,                                                      /* rz.mode        */
    0,                                                      /* rz.xdim        */
    0,                                                      /* rz.ydim        */
    0,      0,                                              /* rz.arg         */
    0,                                                      /* go.order       */
    0,                                                      /* go.mode        */
    0,      0,                                              /* go.offsbuffer  */
    0,      0,                                              /* go.gainbuffer  */
    0,      0,      0,      1320379400,     0,      0,       /* go.arg        */
    0,      0,                                              /* go.dfctbuffer  */
    0,                                                      /* no.order       */
    0,                                                      /* no.mode        */
    0,      0,      0,      0,      0,      0,      0,      0,       /* no.black */
    0,      0,      0,      0,      0,      0,      0,      0,       /* no.coef1 */
    0,      0,      0,      0,      0,      0,      0,      0,       /* no.coef2 */
    0,                                                      /* no.scale       */
    0,      0,      0,                                      /* no.arg         */
    0,                                                      /* sh.order       */
    0,                                                      /* sh.mode        */
    0,      0,      0,                                      /* sh.into        */
    0,      0,      0,                                      /* sh.from        */
    0,                                                      /* sh.scale       */
    0,      0,                                              /* sh.arg         */
    0,      0,      0,      0,                              /* cs2.arg        */
    0,                                                      /* mc.order       */
    0,                                                      /* mc.mode        */
    0,      0,      0,      0,                              /* mc.arg         */
    0,                                                      /* rsvd1          */
};

/*
 * Structure:        pxvidopt
 * Copyright:        (C) EPIX, Inc. 2000-2008
 * Created:        Fri Nov 13 09:47:11 2009
 * By:                EPIX(r)  XCAP V3.0
 * OS:                Linux 64 bit
 */
struct pxvidopt pxvidopt_19_id31232 =
{
    60,                                                     /* ddch.len       */
    19,                                                     /* ddch.mos       */
    0,                                                      /* ddch.id        */
    0,                                                      /* ddch.op        */
    0,                                                      /* ddch.un        */
    0,                                                      /* ddch.rw        */
    0,                                                      /* ddch.fu        */
    0,                                                      /* ddch.rs        */
    0,                                                      /* imopstate      */
    0,                                                      /* imopmode       */
    0,                                                      /* panwraprnd     */
    0,      0,      0,      0,      0,      0,      0,      0,       /* rsvd  */
};

/*
 * Structure:        pxvidmem
 * Copyright:        (C) EPIX, Inc. 2000-2008
 * Created:        Fri Nov 13 09:47:11 2009
 * By:                EPIX(r)  XCAP V3.0
 * OS:                Linux 64 bit
 */
struct pxvidmem pxvidmem_72_id31232 =
{
    528,                                                    /* ddch.len       */
    72,                                                     /* ddch.mos       */
    0,                                                      /* ddch.id        */
    0,                                                      /* ddch.op        */
    0,                                                      /* ddch.un        */
    0,                                                      /* ddch.rw        */
    0,                                                      /* ddch.fu        */
    0,                                                      /* ddch.rs        */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* space */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* start */
    4294967295,     4294967295,     4294967295,     4294967295,     4294967295,     4294967295,     4294967295,     4294967295,
    4294967295,     4294967295,     4294967295,     4294967295,     4294967295,     4294967295,     4294967295,     4294967295,      /* length */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* rsvd  */
};

/*
 * Structure:        pxcamcntl
 * Copyright:        (C) EPIX, Inc. 2000-2008
 * Created:        Fri Nov 13 09:47:11 2009
 * By:                EPIX(r)  XCAP V3.0
 * OS:                Linux 64 bit
 */
struct pxcamcntl pxcamcntl_264_id31232 =
{
    60,                                                     /* ddch.len       */
    264,                                                    /* ddch.mos       */
    0,                                                      /* ddch.id        */
    0,                                                      /* ddch.op        */
    0,                                                      /* ddch.un        */
    0,                                                      /* ddch.rw        */
    0,                                                      /* ddch.fu        */
    0,                                                      /* ddch.rs        */
    30819,                                                  /* fgfamily       */
    23,                                                     /* fgmodel        */
    7183,                                                   /* fgsubmodel     */
    0,                                                      /* fgcustomid     */
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,       /* fgcamera */
    0,      0,      3161564160,     10922,  17301564,       0,      0,      0,
    30819,  23,     7183,   0,      0,      0,      0,      0,       /* rsvd1 */
    4,                                                      /* cntlmode       */
    0,                                                      /* cntlcntinit    */
    328,                                                    /* cntlcntadj     */
    0,                                                      /* cntlcntdeinit  */
    96000,  23988224,       0,      0,      0,      0,      0,      0,       /* cntlparms */
    1,                                                      /* cntlcntxmteot  */
    4,                                                      /* cntlcntrcveot  */
    0,                                                      /* cntloptions    */
    0,                                                      /* cntlcntreset   */
    500,                                                    /* cntlrcvtout    */
    0,                                                      /* cntlrsttout    */
    4,                                                      /* cntlretries    */
    0,                                                      /* cntlpause      */
    0,                                                      /* cntlthrottle   */
    0,      0,      0,      0,      0,      0,      0,       /* rsvd2         */
    0xD0A0D0D,      0x6C0D630A,     0x62343363,     0xD393836,      0x3862796C,     0x34303030,     0x62796C0D,     0x30303030,
    0x796C0D30,     0x30303366,     0x6C0D3030,     0x30303879,     0xD303030,      0x3964796C,     0x61373030,     0x64796C0D,
    0x37303062,     0x796C0D39,     0x30303864,     0x6C0D3030,     0x30616479,     0xD303030,      0x6463796C,     0x30303030,
    0x63796C0D,     0x30303063,     0x796C0D32,     0x30306361,     0x6C0D3030,     0x30386179,     0xD313030,      0x6263796C,
    0x64383030,     0x61796C0D,     0x38303030,     0x796C0D31,     0x30303164,     0x6C0D3032,     0x30666379,     0xD303230,
    0x3266796C,     0x30383030,     0x64796C0D,     0x30303032,     0x796C0D30,     0x30303464,     0x6C0D3036,     0x30336479,
    0xD613030,      0x3064796C,     0x30303030,     0x63796C0D,     0x30303065,     0x796C0D30,     0x30303038,     0x6C0D6330,
    0x30346679,     0xD323330,      0x6365796C,     0x31313030,     0x36796C0D,     0x31303063,     0x796C0D31,     0x30306265,
    0x6C0D3066,     0x30656279,     0xD623430,      0x6533796C,     0x62343030,     0x62796C0D,     0x34303063,     0x796C0D62,
    0x30306333,     0x6C0D6234,     0x30303779,     0xD303430,      0x3137796C,     0x30323030,     0x66796C0D,     0x38303065,
    0x796C0D30,     0x30303838,     0x630D6666,     0xD,    0x0,    0x0,    0x0,    0x0,
    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,
    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,
    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,
    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,
    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,    0x0,     /* cntldata.data32 */
};

/*
 * Structure:        xcsv2format
 * Copyright:        (C) EPIX, Inc. 2000-2008
 * Created:        Fri Nov 13 09:47:11 2009
 * By:                EPIX(r)  XCAP V3.0
 * OS:                Linux 64 bit
 */
struct xcsv2format xcsv2format_32_id31232 =
{
    48,                                                     /* ddch.len       */
    32,                                                     /* ddch.mos       */
    0,                                                      /* ddch.id        */
    0,                                                      /* ddch.op        */
    0,                                                      /* ddch.un        */
    0,                                                      /* ddch.rw        */
    0,                                                      /* ddch.fu        */
    0,                                                      /* ddch.rs        */
    0,                                                      /* Bt8x9format    */
    0,                                                      /* Bt8x9xtal      */
    0,                                                      /* Bt8x9control   */
    0,                                                      /* Bt819oform     */
    0,                                                      /* Bt819vscale    */
    0,                                                      /* Bt819adc       */
    0,                                                      /* Bt829oform     */
    0,                                                      /* Bt829vscale    */
    0,                                                      /* Bt829adc       */
    0,                                                      /* Bt829vtc       */
    0,                                                      /* Bt829scloop    */
    0,                                                      /* Bt848adc       */
    0,                                                      /* Bt848clrctl    */
    0,                                                      /* Bt819options   */
    0,                                                      /* Bt848faultmask */
    0,                                                      /* Bt848haltmask  */
    0,      0,      0,      0,      0,      0,      0,      0,       /* rsvd  */
};

/*
 * Structure:        xcsv2mode
 * Copyright:        (C) EPIX, Inc. 2000-2008
 * Created:        Fri Nov 13 09:47:11 2009
 * By:                EPIX(r)  XCAP V3.0
 * OS:                Linux 64 bit
 */
struct xcsv2mode xcsv2mode_21_id31232 =
{
    40,                                                     /* ddch.len       */
    21,                                                     /* ddch.mos       */
    0,                                                      /* ddch.id        */
    0,                                                      /* ddch.op        */
    0,                                                      /* ddch.un        */
    0,                                                      /* ddch.rw        */
    0,                                                      /* ddch.fu        */
    0,                                                      /* ddch.rs        */
    0,                                                      /* brightness     */
    0,                                                      /* hue            */
    0,                                                      /* lumagain       */
    0,                                                      /* chromaUgain    */
    0,                                                      /* chromaVgain    */
    0,      0,      0,      0,      0,      0,      0,      0,       /* rsvd  */
};

/*
 * Structure:        xcdxxformat
 * Copyright:        (C) EPIX, Inc. 2000-2008
 * Created:        Fri Nov 13 09:47:11 2009
 * By:                EPIX(r)  XCAP V3.0
 * OS:                Linux 64 bit
 */
struct xcdxxformat xcdxxformat_45_id31232 =
{
    124,                                                    /* ddch.len       */
    45,                                                     /* ddch.mos       */
    0,                                                      /* ddch.id        */
    0,                                                      /* ddch.op        */
    0,                                                      /* ddch.un        */
    0,                                                      /* ddch.rw        */
    0,                                                      /* ddch.fu        */
    0,                                                      /* ddch.rs        */
    0x0,                                                    /* PRINC          */
    0x0,                                                    /* EXSYNC         */
    0x1,                                                    /* exsync         */
    0x1,                                                    /* prin           */
    0x0,                                                    /* MWETS          */
    0x0,                                                    /* LCD            */
    0x0,                                                    /* PLLMX          */
    0,                                                      /* clampreference */
    0,                                                      /* pixelclkreference */
    0,      0,                                              /* sdclkfreq      */
    0,                                                      /* SDIET          */
    0x0,                                                    /* PCWD           */
    0x2,                                                    /* CLCCSE         */
    0x0,                                                    /* TEST           */
    0x0,                                                    /* CLCCSEhi       */
    0x0,                                                    /* MSSMUB         */
    0x0,                                                    /* ToucanOpt      */
    0x0,                                                    /* ToucanCoef1    */
    0x0,                                                    /* ToucanCoef2    */
    0x0,                                                    /* ToucanCoef3    */
    0,      0,      0,      0,                              /* exsyncinfo     */
    0,      0,      0,      0,                              /* prininfo       */
    0x0,                                                    /* XXX            */
    0x0,                                                    /* CLCCGP         */
    0x0,                                                    /* MSSMUBhi       */
    0,      0,      0,      0,      0,                      /* rsvd2          */
};
