include ../../Makefile.conf

LINK = g++

MODULE_NAME = HyperGraphsclam Helpers
MODULE_COMMENT =   

CXXFLAGS += -std=c++11 -O0 -g 

IFLAGS += -I$(CARMEN_HOME)/src/hypergraphsclam/Helpers/

SOURCES = StringHelper.cpp

include ../../Makefile.rules
