/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IPC_primFmttrs */

#ifndef _Included_IPC_primFmttrs
#define _Included_IPC_primFmttrs
#ifdef __cplusplus
extern "C" {
#endif
#undef IPC_primFmttrs_INT_FMT
#define IPC_primFmttrs_INT_FMT 1L
#undef IPC_primFmttrs_BOOLEAN_FMT
#define IPC_primFmttrs_BOOLEAN_FMT 2L
#undef IPC_primFmttrs_FLOAT_FMT
#define IPC_primFmttrs_FLOAT_FMT 3L
#undef IPC_primFmttrs_DOUBLE_FMT
#define IPC_primFmttrs_DOUBLE_FMT 4L
#undef IPC_primFmttrs_BYTE_FMT
#define IPC_primFmttrs_BYTE_FMT 5L
#undef IPC_primFmttrs_STR_FMT
#define IPC_primFmttrs_STR_FMT 7L
#undef IPC_primFmttrs_UBYTE_FMT
#define IPC_primFmttrs_UBYTE_FMT 9L
#undef IPC_primFmttrs_CHAR_FMT
#define IPC_primFmttrs_CHAR_FMT 16L
#undef IPC_primFmttrs_SHORT_FMT
#define IPC_primFmttrs_SHORT_FMT 17L
#undef IPC_primFmttrs_LONG_FMT
#define IPC_primFmttrs_LONG_FMT 18L
#undef IPC_primFmttrs_USHORT_FMT
#define IPC_primFmttrs_USHORT_FMT 28L
#undef IPC_primFmttrs_UINT_FMT
#define IPC_primFmttrs_UINT_FMT 29L
#undef IPC_primFmttrs_ULONG_FMT
#define IPC_primFmttrs_ULONG_FMT 30L
#undef IPC_primFmttrs_MAXFORMATTERS
#define IPC_primFmttrs_MAXFORMATTERS 31L
#undef IPC_primFmttrs_CHAR_SIZE
#define IPC_primFmttrs_CHAR_SIZE 1L
#undef IPC_primFmttrs_BYTE_SIZE
#define IPC_primFmttrs_BYTE_SIZE 1L
#undef IPC_primFmttrs_SHORT_SIZE
#define IPC_primFmttrs_SHORT_SIZE 2L
#undef IPC_primFmttrs_INT_SIZE
#define IPC_primFmttrs_INT_SIZE 4L
#undef IPC_primFmttrs_LONG_SIZE
#define IPC_primFmttrs_LONG_SIZE 4L
#undef IPC_primFmttrs_FLOAT_SIZE
#define IPC_primFmttrs_FLOAT_SIZE 4L
#undef IPC_primFmttrs_DOUBLE_SIZE
#define IPC_primFmttrs_DOUBLE_SIZE 8L
#undef IPC_primFmttrs_PTR_SIZE
#define IPC_primFmttrs_PTR_SIZE 4L
/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetChar
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_IPC_primFmttrs_formatGetChar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutChar
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutChar
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetBoolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_IPC_primFmttrs_formatGetBoolean
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutBoolean
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutBoolean
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_IPC_primFmttrs_formatGetByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutByte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutByte
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetUByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_IPC_primFmttrs_formatGetUByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutUByte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutUByte
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetShort
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_IPC_primFmttrs_formatGetShort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutShort
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutShort
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetUShort
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_IPC_primFmttrs_formatGetUShort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutUShort
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutUShort
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_IPC_primFmttrs_formatGetInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetUInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_IPC_primFmttrs_formatGetUInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutUInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutUInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_IPC_primFmttrs_formatGetLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutLong
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_IPC_primFmttrs_formatGetFloat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutFloat
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutFloat
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_IPC_primFmttrs_formatGetDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutDouble
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutDouble
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatGetString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_IPC_primFmttrs_formatGetString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     IPC_primFmttrs
 * Method:    formatPutString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_IPC_primFmttrs_formatPutString
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_LONG_Trans */

#ifndef _Included_IPC_primFmttrs_LONG_Trans
#define _Included_IPC_primFmttrs_LONG_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_UINT_Trans */

#ifndef _Included_IPC_primFmttrs_UINT_Trans
#define _Included_IPC_primFmttrs_UINT_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_USHORT_Trans */

#ifndef _Included_IPC_primFmttrs_USHORT_Trans
#define _Included_IPC_primFmttrs_USHORT_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_BOOLEAN_Trans */

#ifndef _Included_IPC_primFmttrs_BOOLEAN_Trans
#define _Included_IPC_primFmttrs_BOOLEAN_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_DOUBLE_Trans */

#ifndef _Included_IPC_primFmttrs_DOUBLE_Trans
#define _Included_IPC_primFmttrs_DOUBLE_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_FLOAT_Trans */

#ifndef _Included_IPC_primFmttrs_FLOAT_Trans
#define _Included_IPC_primFmttrs_FLOAT_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_CHAR_Trans */

#ifndef _Included_IPC_primFmttrs_CHAR_Trans
#define _Included_IPC_primFmttrs_CHAR_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_INT_Trans */

#ifndef _Included_IPC_primFmttrs_INT_Trans
#define _Included_IPC_primFmttrs_INT_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_SHORT_Trans */

#ifndef _Included_IPC_primFmttrs_SHORT_Trans
#define _Included_IPC_primFmttrs_SHORT_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_UBYTE_Trans */

#ifndef _Included_IPC_primFmttrs_UBYTE_Trans
#define _Included_IPC_primFmttrs_UBYTE_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_BYTE_Trans */

#ifndef _Included_IPC_primFmttrs_BYTE_Trans
#define _Included_IPC_primFmttrs_BYTE_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_STR_Trans */

#ifndef _Included_IPC_primFmttrs_STR_Trans
#define _Included_IPC_primFmttrs_STR_Trans
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class IPC_primFmttrs_TransFormat */

#ifndef _Included_IPC_primFmttrs_TransFormat
#define _Included_IPC_primFmttrs_TransFormat
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
