include $(CARMEN_HOME)/src/Makefile.conf

SUBDIRS += libcarmen_util publish_pose split_log dataset_creator central_log_view user_preferences scripts print_ipc_message # list_camera_ids

MODULE_NAME = UTILITIES
MODULE_COMMENT = Utilitary Scripts

include $(CARMEN_HOME)/src/Makefile.rules
