include $(CARMEN_HOME)/src/Makefile.conf

SUBDIRS += libcarmen_util publish_pose list_camera_ids split_log dataset_creator central_log_view user_preferences scripts compute_time_range

MODULE_NAME = UTILITIES
MODULE_COMMENT = Utilitary Scripts

include $(CARMEN_HOME)/src/Makefile.rules
