include $(CARMEN_HOME)/src/Makefile.conf

MODULE_NAME = "FAKECAM"
MODULE_COMMENT = "Publishes images from a file"

SOURCES = fakecam.c
TARGETS = libfakecam.a 

all: 

libfakecam.a: fakecam.o

# rules

include $(CARMEN_HOME)/src/Makefile.rules
