include ../../Makefile.conf

MODULE_NAME = RRT IPC Messages
MODULE_COMMENT =   

CFLAGS += #-pg #-fopenmp
CXXFLAGS += #-pg #-fopenmp

SOURCES = rrt_planner_interface.cpp

PUBLIC_INCLUDES = rrt_planner_message.h rrt_planner_interface.h

include ../../Makefile.rules
