// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ImageIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <ImageIce.ice.H>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __ImageIceMod__ImageShuttle__transferImage_name = "transferImage";

::Ice::Object* IceInternal::upCast(::ImageIceMod::ImageShuttle* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::ImageIceMod::ImageShuttle* p) { return p; }

void
ImageIceMod::__read(::IceInternal::BasicStream* __is, ::ImageIceMod::ImageShuttlePrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::ImageIceMod::ImageShuttle;
        v->__copyFrom(proxy);
    }
}

void
ImageIceMod::DimsIce::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(w);
    __os->write(h);
}

void
ImageIceMod::DimsIce::__read(::IceInternal::BasicStream* __is)
{
    __is->read(w);
    __is->read(h);
}

void
ImageIceMod::SensorPose::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(val);
    __os->write(weight);
    __os->write(decay);
}

void
ImageIceMod::SensorPose::__read(::IceInternal::BasicStream* __is)
{
    __is->read(val);
    __is->read(weight);
    __is->read(decay);
}

void
ImageIceMod::__write(::IceInternal::BasicStream* __os, ::ImageIceMod::SensorType v)
{
    __os->write(static_cast< ::Ice::Byte>(v), 4);
}

void
ImageIceMod::__read(::IceInternal::BasicStream* __is, ::ImageIceMod::SensorType& v)
{
    ::Ice::Byte val;
    __is->read(val, 4);
    v = static_cast< ::ImageIceMod::SensorType>(val);
}

void
ImageIceMod::SensorVote::__write(::IceInternal::BasicStream* __os) const
{
    ::ImageIceMod::__write(__os, type);
    heading.__write(__os);
    depth.__write(__os);
}

void
ImageIceMod::SensorVote::__read(::IceInternal::BasicStream* __is)
{
    ::ImageIceMod::__read(__is, type);
    heading.__read(__is);
    depth.__read(__is);
}

void
ImageIceMod::WaypointIce::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(x);
    __os->write(y);
    __os->write(depth);
    __os->write(heading);
}

void
ImageIceMod::WaypointIce::__read(::IceInternal::BasicStream* __is)
{
    __is->read(x);
    __is->read(y);
    __is->read(depth);
    __is->read(heading);
}

void
ImageIceMod::Point2DIce::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(i);
    __os->write(j);
}

void
ImageIceMod::Point2DIce::__read(::IceInternal::BasicStream* __is)
{
    __is->read(i);
    __is->read(j);
}

void
ImageIceMod::Point3DIce::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(x);
    __os->write(y);
    __os->write(z);
}

void
ImageIceMod::Point3DIce::__read(::IceInternal::BasicStream* __is)
{
    __is->read(x);
    __is->read(y);
    __is->read(z);
}

void
ImageIceMod::RectangleIce::__write(::IceInternal::BasicStream* __os) const
{
    tl.__write(__os);
    br.__write(__os);
}

void
ImageIceMod::RectangleIce::__read(::IceInternal::BasicStream* __is)
{
    tl.__read(__is);
    br.__read(__is);
}

void
ImageIceMod::QuadrilateralIce::__write(::IceInternal::BasicStream* __os) const
{
    tl.__write(__os);
    tr.__write(__os);
    bl.__write(__os);
    br.__write(__os);
    center.__write(__os);
    __os->write(ratio);
    __os->write(angle);
}

void
ImageIceMod::QuadrilateralIce::__read(::IceInternal::BasicStream* __is)
{
    tl.__read(__is);
    tr.__read(__is);
    bl.__read(__is);
    br.__read(__is);
    center.__read(__is);
    __is->read(ratio);
    __is->read(angle);
}

void
ImageIceMod::LineIce::__write(::IceInternal::BasicStream* __os) const
{
    pt1.__write(__os);
    pt2.__write(__os);
    __os->write(angle);
}

void
ImageIceMod::LineIce::__read(::IceInternal::BasicStream* __is)
{
    pt1.__read(__is);
    pt2.__read(__is);
    __is->read(angle);
}

void
ImageIceMod::ImageIce::__write(::IceInternal::BasicStream* __os) const
{
    if(data.size() == 0)
    {
        __os->writeSize(0);
    }
    else
    {
        __os->write(&data[0], &data[0] + data.size());
    }
    __os->write(width);
    __os->write(height);
    __os->write(pixSize);
}

void
ImageIceMod::ImageIce::__read(::IceInternal::BasicStream* __is)
{
    ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*> ___data;
    __is->read(___data);
    ::std::vector< ::Ice::Byte>(___data.first, ___data.second).swap(data);
    __is->read(width);
    __is->read(height);
    __is->read(pixSize);
}

void
ImageIceMod::__writeImageIceSeq(::IceInternal::BasicStream* __os, const ::ImageIceMod::ImageIce* begin, const ::ImageIceMod::ImageIce* end)
{
    ::Ice::Int size = static_cast< ::Ice::Int>(end - begin);
    __os->writeSize(size);
    for(int i = 0; i < size; ++i)
    {
        begin[i].__write(__os);
    }
}

void
ImageIceMod::__readImageIceSeq(::IceInternal::BasicStream* __is, ::ImageIceMod::ImageIceSeq& v)
{
    ::Ice::Int sz;
    __is->readAndCheckSeqSize(13, sz);
    v.resize(sz);
    for(int i = 0; i < sz; ++i)
    {
        v[i].__read(__is);
    }
}

void
IceProxy::ImageIceMod::ImageShuttle::transferImage(const ::ImageIceMod::ImageIce& i, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
#if defined(__BCPLUSPLUS__) && (__BCPLUSPLUS__ >= 0x0600) // C++Builder 2009 compiler bug
            IceUtil::DummyBCC dummy;
#endif
            __delBase = __getDelegate(false);
            ::IceDelegate::ImageIceMod::ImageShuttle* __del = dynamic_cast< ::IceDelegate::ImageIceMod::ImageShuttle*>(__delBase.get());
            __del->transferImage(i, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::ImageIceMod::ImageShuttle::begin_transferImage(const ::ImageIceMod::ImageIce& i, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __ImageIceMod__ImageShuttle__transferImage_name, __del, __cookie);
    try
    {
        __result->__prepare(__ImageIceMod__ImageShuttle__transferImage_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        i.__write(__os);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::ImageIceMod::ImageShuttle::end_transferImage(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __ImageIceMod__ImageShuttle__transferImage_name);
}

const ::std::string&
IceProxy::ImageIceMod::ImageShuttle::ice_staticId()
{
    return ::ImageIceMod::ImageShuttle::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::ImageIceMod::ImageShuttle::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::ImageIceMod::ImageShuttle);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::ImageIceMod::ImageShuttle::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::ImageIceMod::ImageShuttle);
}

::IceProxy::Ice::Object*
IceProxy::ImageIceMod::ImageShuttle::__newInstance() const
{
    return new ImageShuttle;
}

void
IceDelegateM::ImageIceMod::ImageShuttle::transferImage(const ::ImageIceMod::ImageIce& i, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __ImageIceMod__ImageShuttle__transferImage_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        i.__write(__os);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::ImageIceMod::ImageShuttle::transferImage(const ::ImageIceMod::ImageIce& i, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::ImageIceMod::ImageIce& i, const ::Ice::Current& __current) :
            ::IceInternal::Direct(__current),
            _m_i(i)
        {
        }

        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::ImageIceMod::ImageShuttle* servant = dynamic_cast< ::ImageIceMod::ImageShuttle*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->transferImage(_m_i, _current);
            return ::Ice::DispatchOK;
        }

    private:

        const ::ImageIceMod::ImageIce& _m_i;
    };

    ::Ice::Current __current;
    __initCurrent(__current, __ImageIceMod__ImageShuttle__transferImage_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(i, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::ObjectPtr
ImageIceMod::ImageShuttle::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __ImageIceMod__ImageShuttle_ids[2] =
{
    "::Ice::Object",
    "::ImageIceMod::ImageShuttle"
};

bool
ImageIceMod::ImageShuttle::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__ImageIceMod__ImageShuttle_ids, __ImageIceMod__ImageShuttle_ids + 2, _s);
}

::std::vector< ::std::string>
ImageIceMod::ImageShuttle::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__ImageIceMod__ImageShuttle_ids[0], &__ImageIceMod__ImageShuttle_ids[2]);
}

const ::std::string&
ImageIceMod::ImageShuttle::ice_id(const ::Ice::Current&) const
{
    return __ImageIceMod__ImageShuttle_ids[1];
}

const ::std::string&
ImageIceMod::ImageShuttle::ice_staticId()
{
    return __ImageIceMod__ImageShuttle_ids[1];
}

::Ice::DispatchStatus
ImageIceMod::ImageShuttle::___transferImage(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::ImageIceMod::ImageIce i;
    i.__read(__is);
    __is->endReadEncaps();
    transferImage(i, __current);
    return ::Ice::DispatchOK;
}

static ::std::string __ImageIceMod__ImageShuttle_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "transferImage"
};

::Ice::DispatchStatus
ImageIceMod::ImageShuttle::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__ImageIceMod__ImageShuttle_all, __ImageIceMod__ImageShuttle_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __ImageIceMod__ImageShuttle_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___transferImage(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
ImageIceMod::ImageShuttle::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
ImageIceMod::ImageShuttle::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
ImageIceMod::ImageShuttle::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type ImageIceMod::ImageShuttle was not generated with stream support";
    throw ex;
}

void
ImageIceMod::ImageShuttle::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type ImageIceMod::ImageShuttle was not generated with stream support";
    throw ex;
}
#endif

void
ImageIceMod::__patch__ImageShuttlePtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::ImageIceMod::ImageShuttlePtr* p = static_cast< ::ImageIceMod::ImageShuttlePtr*>(__addr);
    assert(p);
    *p = ::ImageIceMod::ImageShuttlePtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::ImageIceMod::ImageShuttle::ice_staticId(), v->ice_id());
    }
}
