map_reconstruct:
  output_dir: "/dados/sc_lio_sam_output/mapa_localizacao/"
  corner_leaf_size: 0.2
  surf_leaf_size: 0.4
  global_leaf_size: 0.3
  scan_predownsample_leaf: 0.1
  feature_knn: 18
  linearity_thresh: 0.6
  planarity_thresh: 0.6
  accumulate_flush_every: 50
  use_precomputed_global_map: true
  precomputed_global_map_path: "/dados/sc_lio_sam_output/mapa_final_limpo/updated_map.pcd"