include $(CARMEN_HOME)/src/Makefile.conf

MODULE_NAME = LIB_SEG_MAP
MODULE_COMMENT = Library for the segmap module

SUBDIRS += types utils readers motion_models slam visualization datasets initializations

include $(CARMEN_HOME)/src/Makefile.rules
