include ../../Makefile.conf

LINK = g++

MODULE_NAME = HyperGraphSlam Helpers
MODULE_COMMENT =

CXXFLAGS += -std=c++11 -O3

IFLAGS += -I$(CARMEN_HOME)/src/hypergraphslam/Helpers/ -std=c++11 -O3

SOURCES = StringHelper.cpp

include ../../Makefile.rules