include ../../Makefile.conf

CFLAGS += 
IFLAGS += 
LFLAGS += -lflycapture

MODULE_NAME = LIST CAMERA IDS
MODULE_COMMENT = List the ids of the cameras connected to the computer

SOURCES = util_list_camera_ids.cpp
PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES =  
PUBLIC_BINARIES = util_list_camera_ids

TARGETS = util_list_camera_ids

util_list_camera_ids: util_list_camera_ids.o

include ../../Makefile.rules
