// MAE 1.0 - THIS FILE WAS GERNERATED AUTOMATICALY

#include "tracker.h"

void build_network (void)
{
NUM_ISOLATE_NEURON_LAYERS = 36;
NUM_INPUTS = 2;
NUM_OUTPUTS = 5;
NUM_FILTERS = 14;
srand (5); 
memset((void *) &(nl_v1_activation_map), 0, sizeof(NEURON_LAYER));
nl_v1_activation_map.name = "nl_v1_activation_map";
memset((void *) &(nl_target_coordinates), 0, sizeof(NEURON_LAYER));
nl_target_coordinates.name = "nl_target_coordinates";
memset((void *) &(nl_v1_pattern), 0, sizeof(NEURON_LAYER));
nl_v1_pattern.name = "nl_v1_pattern";
memset((void *) &(in_saccade_translated), 0, sizeof(NEURON_LAYER));
in_saccade_translated.name = "in_saccade_translated";
memset((void *) &(in_saccade_translated_gaussian), 0, sizeof(NEURON_LAYER));
in_saccade_translated_gaussian.name = "in_saccade_translated_gaussian";
memset((void *) &(in_pattern_translated), 0, sizeof(NEURON_LAYER));
in_pattern_translated.name = "in_pattern_translated";
memset((void *) &(in_pattern_filtered_translated), 0, sizeof(NEURON_LAYER));
in_pattern_filtered_translated.name = "in_pattern_filtered_translated";
memset((void *) &(in_pattern_filtered_translated_red), 0, sizeof(NEURON_LAYER));
in_pattern_filtered_translated_red.name = "in_pattern_filtered_translated_red";
memset((void *) &(in_pattern_filtered_translated_green), 0, sizeof(NEURON_LAYER));
in_pattern_filtered_translated_green.name = "in_pattern_filtered_translated_green";
memset((void *) &(in_pattern_filtered_translated_blue), 0, sizeof(NEURON_LAYER));
in_pattern_filtered_translated_blue.name = "in_pattern_filtered_translated_blue";
memset((void *) &(table), 0, sizeof(NEURON_LAYER));
table.name = "table";
memset((void *) &(table_v1), 0, sizeof(NEURON_LAYER));
table_v1.name = "table_v1";
memset((void *) &(nl_v1_activation_map_neuron_weight), 0, sizeof(NEURON_LAYER));
nl_v1_activation_map_neuron_weight.name = "nl_v1_activation_map_neuron_weight";
memset((void *) &(nl_activation_map_hough), 0, sizeof(NEURON_LAYER));
nl_activation_map_hough.name = "nl_activation_map_hough";
memset((void *) &(nl_activation_map_hough_gaussian), 0, sizeof(NEURON_LAYER));
nl_activation_map_hough_gaussian.name = "nl_activation_map_hough_gaussian";
memset((void *) &(nl_activation_map_hough_v1), 0, sizeof(NEURON_LAYER));
nl_activation_map_hough_v1.name = "nl_activation_map_hough_v1";
memset((void *) &(nl_activation_map_hough_zoom), 0, sizeof(NEURON_LAYER));
nl_activation_map_hough_zoom.name = "nl_activation_map_hough_zoom";
memset((void *) &(nl_activation_map_hough_zoom_gaussian), 0, sizeof(NEURON_LAYER));
nl_activation_map_hough_zoom_gaussian.name = "nl_activation_map_hough_zoom_gaussian";
memset((void *) &(in_saccade_current), 0, sizeof(INPUT_DESC));
in_saccade_current.name = "in_saccade_current";
memset((void *) &(in_saccade_trained), 0, sizeof(INPUT_DESC));
in_saccade_trained.name = "in_saccade_trained";
memset((void *) &(out_nl_v1_activation_map_neuron_weight), 0, sizeof(OUTPUT_DESC));
out_nl_v1_activation_map_neuron_weight.name = "out_nl_v1_activation_map_neuron_weight";
memset((void *) &(out_table), 0, sizeof(OUTPUT_DESC));
out_table.name = "out_table";
memset((void *) &(out_in_pattern_filtered_translated), 0, sizeof(OUTPUT_DESC));
out_in_pattern_filtered_translated.name = "out_in_pattern_filtered_translated";
memset((void *) &(out_nl_activation_map_hough_zoom), 0, sizeof(OUTPUT_DESC));
out_nl_activation_map_hough_zoom.name = "out_nl_activation_map_hough_zoom";
memset((void *) &(out_nl_activation_map_hough_zoom_gaussian), 0, sizeof(OUTPUT_DESC));
out_nl_activation_map_hough_zoom_gaussian.name = "out_nl_activation_map_hough_zoom_gaussian";

__line = 4;
TYPE_SHOW = SHOW_FRAME;
__line = 5;
TYPE_MOVING_FRAME = STOP;
__line = 6;
CALL_UPDATE_FUNCTIONS = FALSE;
__line = 11;
//;
__line = 17;
//;
__line = 18;
//;
__line = 31;
//;
__line = 34;
//;
__line = 35;
//;
__line = 37;
NEURON_MEMORY_SIZE = 32 * NL_WIDTH * NL_HEIGHT;
__line = 40;
//;
__line = 41;
//;
__line = 42;
//;
__line = 45;
//;
__line = 46;
//;
__line = 49;
translation_filter_deltaX = 0.0;
__line = 50;
translation_filter_deltaY = 0.0;
__line = 52;
translation_filter_deltaX_2 = IMAGE_WIDTH / 2.0;
__line = 53;
translation_filter_deltaY_2 = IMAGE_HEIGHT / 2.0;
__line = 55;
dynamic_scale_factor = 1.0;
__line = 56;
dynamic_scale_factor_init = -1.0;
__line = 57;
g_halph_band_width = 1.0;
__line = 60;
HIGHEST_OUTPUT = 1.0;
__line = 63;
//;
__line = 65;
//;
__line = 66;
//;
__line = 68;
height_in_train = -1.0;
__line = 69;
width_in_train = -1.0;
__line = 72;
g_kernel_size = 5;
__line = 73;
g_sigma = 1.0;
__line = 78;
create_neuron_layer (&nl_v1_activation_map, &minchinton, GREYSCALE, COLOR, NL_WIDTH,NL_HEIGHT,SHARED_MEMORY, NEURON_MEMORY_SIZE);
__line = 80;
create_neuron_layer (&nl_target_coordinates, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, 2,1,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 82;
create_neuron_layer (&nl_v1_pattern, NULL, NOT_SPECIFIED, COLOR, NL_WIDTH,NL_HEIGHT,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 84;
create_neuron_layer (&in_saccade_translated, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH * 2,IMAGE_HEIGHT * 2,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 85;
create_neuron_layer (&in_saccade_translated_gaussian, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH * 2,IMAGE_HEIGHT * 2,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 87;
create_neuron_layer (&in_pattern_translated, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 88;
create_neuron_layer (&in_pattern_filtered_translated, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 89;
create_neuron_layer (&in_pattern_filtered_translated_red, NULL, NOT_SPECIFIED, GREYSCALE, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 90;
create_neuron_layer (&in_pattern_filtered_translated_green, NULL, NOT_SPECIFIED, GREYSCALE, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 91;
create_neuron_layer (&in_pattern_filtered_translated_blue, NULL, NOT_SPECIFIED, GREYSCALE, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 93;
create_neuron_layer (&table, NULL, NOT_SPECIFIED, COLOR, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 94;
create_neuron_layer (&table_v1, NULL, NOT_SPECIFIED, COLOR, NL_WIDTH,NL_HEIGHT,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 96;
create_neuron_layer (&nl_v1_activation_map_neuron_weight, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, NL_WIDTH,NL_HEIGHT,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 98;
create_neuron_layer (&nl_activation_map_hough, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 99;
create_neuron_layer (&nl_activation_map_hough_gaussian, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 100;
create_neuron_layer (&nl_activation_map_hough_v1, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, NL_WIDTH,NL_HEIGHT,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 102;
create_neuron_layer (&nl_activation_map_hough_zoom, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, TAM_NL_ZOOM,1,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 103;
create_neuron_layer (&nl_activation_map_hough_zoom_gaussian, NULL, NOT_SPECIFIED, GREYSCALE_FLOAT, TAM_NL_ZOOM,1,DISTRIBUTED_MEMORY, NEURON_MEMORY_SIZE);
__line = 110;
create_output (&out_nl_v1_activation_map_neuron_weight, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED, output_handler_weighted_average_value_position, "%s %f", TARGET_NEURON_LAYER_NAME, LOG_FACTOR);
__line = 112;
create_output (&out_table, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED, NULL, 0);
__line = 114;
create_output (&out_in_pattern_filtered_translated, IMAGE_WIDTH_RESIZED,IMAGE_HEIGHT_RESIZED, NULL, 0);
__line = 116;
create_output (&out_nl_activation_map_hough_zoom, TAM_NL_ZOOM,1, output_handler_resize, "%f", LOG_FACTOR);
__line = 118;
create_output (&out_nl_activation_map_hough_zoom_gaussian, TAM_NL_ZOOM,1, output_handler_resize, "%f", LOG_FACTOR);
__line = 122;
create_input (&in_saccade_current, IMAGE_WIDTH,IMAGE_HEIGHT, COLOR, 0, REGULAR_PYRAMID, input_generator, input_controler, " ", " ");
__line = 124;
create_input (&in_saccade_trained, IMAGE_WIDTH,IMAGE_HEIGHT, COLOR, 0, REGULAR_PYRAMID, input_generator2, input_controler2, " ", " ");
__line = 129;
create_filter (translate_nl_filter, &in_saccade_translated, 1, in_saccade_current.neuron_layer, "%p %p", &translation_filter_deltaX, &translation_filter_deltaY);
__line = 131;
create_filter (translate_nl_filter_3, &in_pattern_translated, 1, &in_saccade_translated, "%p %p", &translation_filter_deltaX_2, &translation_filter_deltaY_2);
__line = 133;
create_filter (gaussian_filter, &in_pattern_filtered_translated, 1, &in_pattern_translated, "%d %f", 5, 1.0);
__line = 134;
create_filter (red_mask_filter, &in_pattern_filtered_translated_red, 1, &in_pattern_filtered_translated, "");
__line = 135;
create_filter (green_mask_filter, &in_pattern_filtered_translated_green, 1, &in_pattern_filtered_translated, "");
__line = 136;
create_filter (blue_mask_filter, &in_pattern_filtered_translated_blue, 1, &in_pattern_filtered_translated, "");
__line = 139;
create_filter (map_image_v1, &nl_v1_pattern, 1, &in_pattern_filtered_translated, "%s %f", "", LOG_FACTOR);
__line = 141;
create_filter (compute_weigheted_neighboor_filter, &nl_v1_activation_map_neuron_weight, 1, &nl_v1_activation_map, "%f", LOG_FACTOR);
__line = 143;
create_filter (map_image_v1, &table_v1, 1, &table, "%s %f", "", LOG_FACTOR);
__line = 145;
create_filter (generate_hough_activation_map, &nl_activation_map_hough, 1, &nl_v1_activation_map, "%f", LOG_FACTOR);
__line = 146;
create_filter (gaussian_filter, &nl_activation_map_hough_gaussian, 1, &nl_activation_map_hough, "%d %f", 5, 0.5);
__line = 147;
create_filter (map_image_v1, &nl_activation_map_hough_v1, 1, &nl_activation_map_hough_gaussian, "%s %f", "", LOG_FACTOR);
__line = 149;
create_filter (generate_hough_zoom_activation_map, &nl_activation_map_hough_zoom, 1, &nl_v1_activation_map, "%f", LOG_FACTOR);
__line = 151;
create_filter (gaussian_filter, &nl_activation_map_hough_zoom_gaussian, 1, &nl_activation_map_hough_zoom, "%d %f", 13, 2.0);
__line = 159;
output_connect (&nl_activation_map_hough, &out_nl_v1_activation_map_neuron_weight);
__line = 161;
output_connect (&table, &out_table);
__line = 163;
output_connect (&in_pattern_filtered_translated, &out_in_pattern_filtered_translated);
__line = 165;
output_connect (&nl_activation_map_hough_zoom, &out_nl_activation_map_hough_zoom);
__line = 167;
output_connect (&nl_activation_map_hough_zoom_gaussian, &out_nl_activation_map_hough_zoom_gaussian);
__line = 172;
associate_neurons (&nl_v1_activation_map, &nl_v1_activation_map);
__line = 179;
connect_neurons (LOG, &in_pattern_filtered_translated_red, &nl_v1_activation_map, INPUTS_PER_NEURON, GAUSSIAN_RADIUS, LOG_FACTOR,0 , -1,-1,-1,-1, -1,-1,-1,-1, SAME_INTERCONNECTION_PATTERN);
__line = 180;
connect_neurons (LOG, &in_pattern_filtered_translated_green, &nl_v1_activation_map, INPUTS_PER_NEURON, GAUSSIAN_RADIUS, LOG_FACTOR,0 , -1,-1,-1,-1, -1,-1,-1,-1, SAME_INTERCONNECTION_PATTERN);
__line = 181;
connect_neurons (LOG, &in_pattern_filtered_translated_blue, &nl_v1_activation_map, INPUTS_PER_NEURON, GAUSSIAN_RADIUS, LOG_FACTOR,0 , -1,-1,-1,-1, -1,-1,-1,-1, SAME_INTERCONNECTION_PATTERN);
__line = 188;
create_interpreter_user_function (INT_TYPE, run_train, "run_train", "%d");
;
__line = 189;
create_interpreter_user_function (INT_TYPE, run_test, "run_test", "%d");
;
map_layers2id (); 
count_num_neurons (); 
initialise_memory (); 
create_io_windows (); 
}
