default: all

all:
	@cd ./libjaus; make;
	@cd ./libopenJaus; make;
	@cd ./ojNodeManager; make;
	@cd ./ojVehicleSim; make;
	@cd ./ojTorc; make;
	@cd ./ojIARASim; make;
	@cd ./ojSteeringBypass; make;
	@cd ./ojCanStimulus; make;

clean:
	@cd ./libjaus; make clean;
	@cd ./libopenJaus; make clean;
	@cd ./ojNodeManager; make clean;
	@cd ./ojVehicleSim; make clean;
	@cd ./ojTorc; make clean;
	@cd ./ojIARASim; make clean;
	@cd ./ojSteeringBypass; make clean;
	@cd ./ojCanStimulus; make clean;

