SET MAP_PATH=../data/map_argos_holofre_20260514

SET MAP_X=1000.0
SET MAP_Y=1000.0

#SET LOG_NAME=log_argos_imu-2.txt
#SET LOG_NAME=log_argos_imu-3.txt
#SET LOG_NAME=log_argos_imu-4.txt
#SET LOG_NAME=log_argos_20262506_lcad_to_honofre.txt
SET LOG_NAME=log_argos_20262506_honofre_to_lcad4.txt
#SET LOG_NAME=log_argos_20262506_ic2.txt

#SET SC_LIO_SAM_MAP_PATH=/dados/sc_lio_sam_output/map_lcad_honofre/
SET SC_LIO_SAM_MAP_PATH=/dados/sc_lio_sam_output/map_honofre_lcad/


SET START_X= 0.0
SET START_Y= 0.0
SET START_Z= 0.0
SET START_ROLL= 0.0
SET START_PITCH= 0.0
SET START_THETA= 0.0


SET CALIBRATION_FILE=calibration_table.txt
SET PARAM_FILE=argos/carmen-argos.ini
SET PARAM_SC_LIO_SAM=argos/params_argos.yaml

# Exemplo de entrada de proccontrol:
# module name			group_name	requested_state		watch_heartbeats	command_line

#### Serviccos de suporte
 param_daemon			support		1		0		./param_daemon ${PARAM_FILE}
 proc_control			support		1		0		./proccontrol_gui
 playback 			support 	1		0		./playback /dados/${LOG_NAME}
 playback_control		support 	1		0		./playback_control -message 't 0.0 '

 map_server			support		1		0		./map_server -map_path ${MAP_PATH} -map_x ${MAP_X} -map_y ${MAP_Y} -block_map on  -lanemap_incoming_message_type 0

#### SLAM
 fused_odometry			SLAM 		1		0		./fused_odometry -use_gps off -force_initial_pose on -initial_x ${START_X} -initial_y ${START_Y} -initial_theta ${START_THETA}
 mapper				SLAM		1		0		./mapper -map_path ${MAP_PATH}
 
#### Interfaces
 viewer_3D			interface	1		0		./viewer_3D
 Cam_view			interface	0		0		./camera_viewer unitree1 1
 Cam_view_lat			interface	0		0		./camera_viewer 4

#### SC-LIO-SAM
 SC-LIO-SAM			ros		1		0		sleep 1 && source ../src/ros1_sc_lio_sam/devel/setup.bash && roslaunch lio_sam run.launch localizationMode:=false params_file:=${PARAM_SC_LIO_SAM} savePCDDirectory:=${SC_LIO_SAM_MAP_PATH} initialPoseX:=${START_X} initialPoseY:=${START_Y} initialPoseZ:=${START_Z} initialPoseRoll:=${START_ROLL} initialPosePitch:=${START_PITCH} initialPoseYaw:=${START_THETA}
 ros_bridge			ros		1		0		source ../src/ros1_sc_lio_sam/devel/setup.bash && roslaunch carmen_ipc_bridge carmen_ipc_bridge.launch
 
 
