### Esse process foi feito para rodar modulos de sensores no argos e o restante do carmen fora do argos, para fazer isso rode os seguinte comandos em terminais separados no argos (depois de abrir a vcan)
# ../sharedlib/OpenJAUS/ojNodeManager/bin/ojNodeManager ../sharedlib/OpenJAUS/ojNodeManager/nodeManager_Argos.conf a
# ../sharedlib/OpenJAUS/ojArgos/bin/ojArgos vcan0 vcan0
# source ~/I2CA/argos/scripts/setup_argos.bash && ros2 run argos_drivers_cpp can_to_wirelesscontroller
# source ~/I2CA/argos/scripts/setup_argos.bash && ros2 run argos_drivers_cpp ros_to_carmen_odometry > ros_odometry.txt
# export CENTRALHOST=192.168.123.99 && ./xsens_argos
# export CENTRALHOST=192.168.123.99 && ./hesai_driver -lidar_id 5

# Parâmetros de comunicação
SET ODOM_CAN_BUS=vcan0
SET COMMAND_CAN_BUS=vcan0

# Parâmetro do local do mapa
SET MAP_PATH=/dados/sc_lio_sam_output/lcad2/map2d

SET LOG_PATH=log_loop_ct13.txt

SET LIDAR_SENSOR_ID=5

# Parâmetros de visualização do mapa no Gui
SET MAP_X=1000.0
SET MAP_Y=1000.0

# Posição inicial do Robo no mapa
SET INITIAL_X=1000.0
SET INITIAL_Y=1000.0
SET INITIAL_THETA=-3.086
SET ORIGIN_THETA=0.0
SET START_X=1000.0
SET START_Y=1000.0
SET START_THETA=0.0

# Posição do objetivo final (Final goal)
SET GOAL_X=1028.30
SET GOAL_Y=993.82
SET GOAL_THETA=-1.072

# Missão do robo
SET MISSION=argos/mission_go_to_ct13.txt

# Localização do Graph
#SET GRAPH=graph-ct13-copiadora.gr
#SET GRAPH=graph-copiadora-ct13-2.gr
SET GRAPH=graph-rddf_lcad.gr

SET SC_LIO_SAM_MAP_PATH=/dados/sc_lio_sam_output/lcad2/

# Annotations (RDDF)
#SET ANNOTATIONS=argos/argos-rddf-ct13.txt

# Arquivo de calibração
SET CALIBRATION_FILE=calibration_table.txt

## Origem do mundo (no lugar do map_world_origin.txt da IARA -- ver cabecalho)
SET ORIGIN_X=7757339.037
SET ORIGIN_Y=-363784.117
SET ORIGIN_Z=0.0
SET ORIGIN_YAW=0.0
SET START_X= 0.0
SET START_Y= 0.0
SET START_Z= 0.0
SET START_ROLL= 0.0
SET START_PITCH= 0.0
SET START_THETA= 0.0
SET PARAM_SC_LIO_SAM=argos/params_argos.yaml

# Exemplo de entrada de proccontrol:
# module name		group_name	requested_state		watch_heartbeats	command_line

#### Serviccos de suporte
 jaus		 		support 	1		0		../sharedlib/OpenJAUS/ojNodeManager/bin/ojNodeManager ../sharedlib/OpenJAUS/ojNodeManager/nodeManager_Argos_CCU.conf a
 car_driver	  		support 	0		0		../sharedlib/OpenJAUS/ojArgos/bin/ojArgos ${ODOM_CAN_BUS} ${COMMAND_CAN_BUS}
 param_daemon			support	1		0		./param_daemon argos/carmen-argos.ini
 proc_control			support	1		0		./proccontrol_gui
 map_server			support	1		0		./map_server -map_path ${MAP_PATH} -map_x ${MAP_X} -map_y ${MAP_Y} -block_map on  -lanemap_incoming_message_type 0
 joystick			support	0		0		./joystick_vehicle -direct_v_and_phi_mode on

#### Robo
 ford_escape			robot		1		0		./ford_escape_hybrid -robot_model_name 4 -tune_pid_mode on > results_pid.txt
 base_ackerman			robot		1		0		./base_ackerman
  
#### Sensores
 camera1			sensors	0		0		./camera_drivers unitree1 1
 camera_lateral		sensors	0		0		./camera_drivers intelbras4 4
 
#### Processamento dos dados dos Sensores
 gps_xyz			sensor_filter	1		0		./gps_xyz

#### SLAM
 fused_odometry		SLAM		0		0		./fused_odometry -use_gps off -force_initial_pose on -initial_x ${INITIAL_X} -initial_y ${INITIAL_Y} -initial_theta ${INITIAL_THETA}
 localize			SLAM	1			0		./localize_ackerman -mapping_mode on
 mapper			SLAM		1		0		./mapper -map_path ${MAP_PATH}
 mapper_creator		SLAM		0		0		./mapper -map_path ${MAP_PATH} -mapping_mode on  -calibration_file ${CALIBRATION_FILE}
 od_mapper			SLAM		1		0		./obstacle_distance_mapper
 rndf_build			SLAM		0		0		./rddf_build ../data/rndf/rddf-ct13-corredor-20250903.txt

#### Hierarquia de controle (top-down)
 task_manager 			planner 	0		0		./task_manager -start_delay off -mission ${MISSION}
 route_planner			planner	0		0		./route_planner --graph ${MAP_PATH}/../graphs/${GRAPH} ${MAP_PATH}/../annotations/annotations.txt
 offroad_planner  		planner	0		0		./offroad_planner
 behavior_selector		planner	0		0		./behavior_selector
 MPP				planner   	0		0		./model_predictive_planner
 obstacle_avoider   		planner 	0		0		./obstacle_avoider

#### Interfaces
 navigator_gui			interface	1		0		./navigator_gui2 -map_path ${MAP_PATH} -annotation_path ${MAP_PATH}/../annotations/annotations.txt
 viewer_3D			interface	0		0		./viewer_3D
 Cam_view			interface	0		0		./camera_viewer unitree1 1
 Cam_view_lat			interface	0		0		./camera_viewer 4

#### Utilitarios
 fake_gps			utils		0		0		./util_publish_pose 20 ${START_X} ${START_Y} ${START_THETA}
 util_publish_initial_pose   	utils		0		0		./util_publish_initial_pose	${ORIGIN_X}, ${ORIGIN_y}, ${ORIGIN_YAW}, 4, 0.0
 util_publish_final_goal	utils		0		0		./util_publish_final_goal    ${GOAL_X} ${GOAL_Y} ${GOAL_THETA} 5
 LOG_CREATE			utils		0		0		./logger /dados/${LOG_PATH}
 
#### ROS / SC-LIO-SAM
 ros_bridge          ros           1        0      source ../src/sc_lio_sam/devel/setup.bash && roslaunch carmen_ipc_bridge carmen_ipc_bridge.launch lidar_sensor_id:=${LIDAR_SENSOR_ID} use_sim_time:=true > caco_bridge.txt
 SC-LIO-SAM          ros           1        0      sleep 1 && source ../src/sc_lio_sam/devel/setup.bash && roslaunch lio_sam run.launch localizationMode:=true params_file:=${PARAM_SC_LIO_SAM} savePCDDirectory:=${SC_LIO_SAM_MAP_PATH} initialPoseX:=${START_X} initialPoseY:=${START_Y} initialPoseZ:=${START_Z} initialPoseRoll:=${START_ROLL} initialPosePitch:=${START_PITCH} initialPoseYaw:=${START_THETA} use_sim_time:=true > caco_sclio.txt

#### injecao da localizacao (ligar SO' depois do robo encaixar no mapa)
 fused_odom_slam     ros           1        0      source ../src/sc_lio_sam/devel/setup.bash && rosrun carmen_ipc_bridge fused_odometry_from_slam_node _origin_x:=${ORIGIN_X} _origin_y:=${ORIGIN_Y} _origin_z:=${ORIGIN_Z} _origin_yaw:=${ORIGIN_YAW} > caco_fused.txt 2>&1
 
