#SET MAP_PATH=../data/map_argos_honofre_18112025
#SET MAP_PATH=../data/map_argos_grid_res_005
#SET MAP_PATH=../data/mapper_teste2
#SET MAP_PATH=../data/map_argos_arcelor_20260429-2
SET MAP_PATH=../data/map_argos_holofre_20260514
#SET MAP_PATH=../data/argos_data/map_argos_log_argos_lcad4-20260512-1
SET MAP_X=1000.0
SET MAP_Y=1000.0

#SET LOG_NAME=log_argos_lcad4-20260512-1.txt
SET LOG_NAME=log_argos_ct13_20260611-4.txt

#SET LOG_PATH=/dados/log_argos_arcelor_04222026-3.txt
#SET LOG_PATH=/dados/log_lcad4_argos-20260506-2.txt
#SET LOG_PATH=/dados/log_argos_lcad4-20260514-2.txt
#SET LOG_PATH=/dados/log_argos_arcelor_04222026-2.txt
#SET LOG_PATH=/dados/log_argos_lcad4-20260514-1.txt


#SET ANNOTATION= argos/argos-rddf-ct13.txt
#SET ANNOTATION=${MAP_PATH}/annotation/annotation_argos.txt
 
#SET RDDF_NAME=rddf-argos_arcelor_04222026-2-1.txt
#SET RDDF_NAME=log_argos_lcad4-20260514-2.txt
#SET RDDF_NAME=${MAP_PATH}/rddf/rddf_argos_${LOG_NAME}

SET START_X=1000.0
SET START_Y=1000.0
SET START_THETA=-1.57
SET CALIBRATION_FILE=calibration_table.txt
SET PARAM_FILE=argos/carmen-argos.ini

# Exemplo de entrada de proccontrol:
# module name			group_name	requested_state		watch_heartbeats	command_line

#### Serviccos de suporte
 param_daemon			support		1		0		./param_daemon ${PARAM_FILE}
 proc_control			support		1		0		./proccontrol_gui
 playback 			support 	1		0		./playback /dados/${LOG_NAME}
 playback_control		support 	1		0		./playback_control -message 't 0.0 '

 map_server			support		1		0		./map_server -map_path ${MAP_PATH} -map_x ${MAP_X} -map_y ${MAP_Y} -block_map on  -lanemap_incoming_message_type 0

#### Robo
 base_ackerman			robot		1		0		./base_ackerman
 
#### Sensores
# XSENS_fake			sensors		1		0		./xsens_mtig -disable_xsens on
 
#### Processamento dos dados dos Sensores
 gps_xyz			sensor_filter	1		0		./gps_xyz

#### SLAM
 fused_odometry			SLAM 		1		0		./fused_odometry -use_gps off -force_initial_pose on -initial_x ${START_X} -initial_y ${START_Y} -initial_theta ${START_THETA}
 localize			SLAM		1		0		./localize_ackerman -mapping_mode off -calibration_file calibration_table.txt
 mapper				SLAM		1		0		./mapper -map_path ${MAP_PATH}
 mapper_creator			SLAM		0		0		./mapper -map_path ${MAP_PATH} -mapping_mode on  
 od_mapper			SLAM		1		0		./obstacle_distance_mapper
 rndf_build			SLAM		0		0		./rddf_build ${MAP_PATH}/rddf/rddf_argos_${LOG_NAME}

#### Interfaces
 navigator_gui			interface	1		0		./navigator_gui2 -map_path ${MAP_PATH} -annotation_path ${MAP_PATH}/annotation/annotation_argos.txt
 viewer_3D			interface	1		0		./viewer_3D
 Cam_view			interface	1		0		./camera_viewer unitree1 1
 Cam_view_lat			interface	1		0		./camera_viewer 4

 fake_gps			utils		0		0		./util_publish_pose 20 ${START_X} ${START_Y} ${START_THETA}
 gps_from_globalpos		utils		0		0		./util_publish_gps_from_globalpos 31 1

 util_publish_initial_pose   	init_pose	0		0		./util_publish_initial_pose	${START_X}, ${START_Y}, ${START_THETA}, 4, 0.0
 
