include ../../Makefile.conf

LINK = g++

MODULE_NAME = RRT Path Follower
MODULE_COMMENT =   
CFLAGS += #-pg #-fopenmp
CXXFLAGS += #-pg  #-fopenmp

SOURCES = follower.cpp path_follower_ackerman.cpp

include ../../Makefile.rules
