include ../../Makefile.conf

LINK = g++

MODULE_NAME = RRT Path Follower
MODULE_COMMENT =   
CFLAGS += #-fopenmp
CXXFLAGS +=  #-fopenmp

SOURCES = follower.cpp path_follower_ackerman.cpp

include ../../Makefile.rules
