#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := arm_horizontal_control_and_steering_angle_reading

include $(IDF_PATH)/make/project.mk
