include ../../Makefile.conf

LINK = g++

MODULE_NAME = HyperGraphSclam Custom Edges
MODULE_COMMENT =

CXXFLAGS += -std=c++11 -O3

IFLAGS += -I$(CARMEN_HOME)/src/hypergraphslam/CustomEdges/ -std=c++11 -O3

include ../../Makefile.rules