#!/bin/bash

function make_module()
{
	cd "$CARMEN_HOME/src/$1"
	if [ "$2" = "-ignore_errors" ]; then
		echo "$1"
		make &> /dev/null
	else
		make
	fi
}


function make_list_of_modules()
{
	for mod in $1; do
		ERROR=1
		if [ -d "$CARMEN_HOME/src/$mod" ]; then
			make_module "$mod" "$2"
			ERROR=$?
		fi
		if [ $ERROR -ne 0 ] && [ "$2" != "-ignore_errors" ]; then
			exit 1
		fi
	done
}


$CARMEN_HOME/bin/make_clean_all

PREPARATION="web_cam tracker lane_detector path_planner camera . camera velodyne_camera_calibration 
	     camera_boxes_to_world ../sharedlib/libclustering web_cam laser-ldmrs tracker 
	     lane_detector dynamic_object_detector voice_interface voice_interface/libvoice"

MODULES="." # May include other modules separated by spaces

echo -e "\nPreparation...\n"
make_list_of_modules "$PREPARATION" -ignore_errors

make_list_of_modules "$MODULES"

