include $(CARMEN_HOME)/src/Makefile.conf

MODULE_NAME = Utility Scripts
MODULE_COMMENT = Scripts for utility tasks 

TARGETS = \
	$(CARMEN_HOME)/bin/filetypes.sh \
	$(CARMEN_HOME)/bin/gdown.pl \
	$(CARMEN_HOME)/bin/grep_all \
	$(CARMEN_HOME)/bin/make_all \
	$(CARMEN_HOME)/bin/make_clean_all \
	$(CARMEN_HOME)/bin/make_log \
	$(CARMEN_HOME)/bin/mv_log.sh \
	$(CARMEN_HOME)/bin/publish_pose_from_annotation \
	$(CARMEN_HOME)/bin/rebuild_caffe \
	$(CARMEN_HOME)/bin/timestamp_graph \

$(CARMEN_HOME)/bin/filetypes.sh:
	ln -s  $(PWD)/filetypes.sh  $(CARMEN_HOME)/bin/

$(CARMEN_HOME)/bin/gdown.pl:
	ln -s  $(PWD)/gdown.pl  $(CARMEN_HOME)/bin/

$(CARMEN_HOME)/bin/grep_all:
	ln -s  $(PWD)/grep_all  $(CARMEN_HOME)/bin/

$(CARMEN_HOME)/bin/make_all:
	ln -s  $(PWD)/make_all  $(CARMEN_HOME)/bin/

$(CARMEN_HOME)/bin/make_clean_all:
	ln -s  $(PWD)/make_clean_all  $(CARMEN_HOME)/bin/

$(CARMEN_HOME)/bin/make_log:
	ln -s  $(PWD)/make_log  $(CARMEN_HOME)/bin/

$(CARMEN_HOME)/bin/mv_log.sh:
	ln -s  $(PWD)/mv_log.sh  $(CARMEN_HOME)/bin/

$(CARMEN_HOME)/bin/publish_pose_from_annotation:
	ln -s  $(PWD)/publish_pose_from_annotation  $(CARMEN_HOME)/bin/

$(CARMEN_HOME)/bin/rebuild_caffe:
	ln -s  $(PWD)/rebuild_caffe  $(CARMEN_HOME)/bin/

$(CARMEN_HOME)/bin/timestamp_graph:
	ln -s  $(PWD)/timestamp_graph  $(CARMEN_HOME)/bin/

include $(CARMEN_HOME)/src/Makefile.rules
