#!/bin/bash

function make_module()
{
	cd "$CARMEN_HOME/src/$1"
	if [ "$2" = "-ignore_errors" ]; then
		echo "$1"
		make &> /dev/null
	else
		make
	fi
}


function make_list_of_modules()
{
	for mod in $1; do
		ERROR=1
		if [ -d "$CARMEN_HOME/src/$mod" ]; then
			make_module "$mod" "$2"
			ERROR=$?
		fi
		if [ $ERROR -ne 0 ] && [ "$2" != "-ignore_errors" ]; then
			exit 1
		fi
	done
}


$CARMEN_HOME/bin/make_clean_all

PREPARATION="ford_escape_hybrid  road_mapper  sensors/kinect  traffic_light  lane_detector  .  voice_interface 
			 ford_escape_hybrid  road_mapper  sensors/kinect  traffic_light  lane_detector  voice_interface  .
			 ford_escape_hybrid  dynamic_object_detector"


MODULES="." # May include other modules separated by spaces

echo -e "\nPreparation...\n"
make_list_of_modules "$PREPARATION" -ignore_errors

make_list_of_modules "$MODULES"

