#!/bin/bash

make_clean_module()
{
	cd $CARMEN_HOME/src/$1
	make clean
}

rm_symbolic_links()
{
	cd $1
	rm $(ls -l --time-style=full-iso | grep ' \-> ' | cut -d':' -f 3 | cut -d' ' -f 3)
}

MODULES=". ../sharedlib 
	 sensors/camera clean_map cvis graphslam hypergraphsclam lane_detector laser_calibration moving_objects2 
	 path_planner slam6d slam_icp tracker velodyne_icp virtual_scan visual_graphslam voslam sensors/web_cam road_mapper
	 lane_detection laser_ldmrs logtools mapper_datmo moving_obstacle_detector mvog_package navigator_ackerman
	 navigator_astar neural_object_detector voice_interface voice_interface/libvoice voice_interface/libvoice_google"

ERRORS=

rm_symbolic_links $CARMEN_HOME/lib
rm_symbolic_links $CARMEN_HOME/include/carmen

for mod in $MODULES
do
	ERROR_MODULE=1
	if [ -d $CARMEN_HOME/src/$mod ]
	then
		make_clean_module $mod
		ERROR_MODULE=$?
	fi
	if [ ! $ERROR_MODULE -eq 0 ]
	then
		ERRORS="$ERRORS $mod"
	fi
done

if [ "$ERRORS" != "" ]
then
	echo ========================
	echo Errors found in modules:$ERRORS
	echo ========================
fi

