include $(CARMEN_HOME)/src/Makefile.conf

MODULE_NAME = Utility Scripts
MODULE_COMMENT = Scripts for utility tasks 

PUBLIC_OTHERS = \
	filetypes.sh \
	gdown.pl \
	grep_all \
	make_log \
	mv_log.sh \
	publish_pose_from_annotation \
	rebuild_caffe \
	timestamp_graph \
#	make_all \
#	make_clean_all \


include $(CARMEN_HOME)/src/Makefile.rules
