######################################################################
# Automatically generated by qmake (2.01a) qua nov 28 14:52:14 2012
######################################################################

TEMPLATE = app
TARGET = proccontrol_gui
DEPENDPATH += .
INCLUDEPATH += ../../include
LIBS += -L../../lib -lcarmenserial -lglobal -lipc -lz -L ./ -lvoice_interface_interface -lespeak
LIBS += -luser_preferences
QMAKE_CXXFLAGS += -Wno-write-strings
QMAKE_CFLAGS += -Wno-write-strings
CONFIG += c++17

# Input
HEADERS += proccontrol.h \
           proccontrol_gui.h \
           proccontrol_interface.h \
           proccontrol_messages.h 
SOURCES += proccontrol_gui.cpp \
           proccontrol_interface.c 
QT += core gui widgets
