include $(CARMEN_HOME)/src/Makefile.conf

SUBDIRS += pid mpc rlpid

MODULE_NAME = LIBCONTROL
MODULE_COMMENT = Low Level Control Library

#IFLAGS += -I$(CARMEN_HOME)/sharedlib/libcontrol/pid
#IFLAGS += -I$(CARMEN_HOME)/sharedlib/libcontrol/mpc

#LFLAGS += -L$(CARMEN_HOME)/sharedlib/libcontrol/pid
#LFLAGS += -L$(CARMEN_HOME)/sharedlib/libcontrol/mpc

#TARGETS = libcontrol.a  

#libcontrol.a: mpc.o pid.o

include $(CARMEN_HOME)/src/Makefile.rules
