include $(CARMEN_HOME)/src/Makefile.conf

MODULE_NAME = SHAREDLIB EXAMPLE LIBA
MODULE_COMMENT = Sharedlib example liba

SOURCES = a.cpp
PUBLIC_INCLUDES = a.h
PUBLIC_LIBRARIES = liba.so

TARGETS = liba.so

liba.so: a.o

include $(CARMEN_HOME)/src/Makefile.rules

