sudo: false

language: python

os:
  - linux

git:
  depth: false

before_install:
  - git submodule update --init --recursive

stages:
  - build
  - deploy

jobs:
  include:

    - name: "Build Arduino 0"
      if: tag IS blank AND (type = pull_request OR (type = push AND branch = master))
      stage: build
      script: $TRAVIS_BUILD_DIR/.github/scripts/on-push.sh 0 10

    - name: "Build Arduino 1"
      if: tag IS blank AND (type = pull_request OR (type = push AND branch = master))
      stage: build
      script: $TRAVIS_BUILD_DIR/.github/scripts/on-push.sh 1 10

    - name: "Build Arduino 2"
      if: tag IS blank AND (type = pull_request OR (type = push AND branch = master))
      stage: build
      script: $TRAVIS_BUILD_DIR/.github/scripts/on-push.sh 2 10

    - name: "Build Arduino 3"
      if: tag IS blank AND (type = pull_request OR (type = push AND branch = master))
      stage: build
      script: $TRAVIS_BUILD_DIR/.github/scripts/on-push.sh 3 10

    - name: "Build PlatformIO"
      if: tag IS blank AND (type = pull_request OR (type = push AND branch = master))
      stage: build
      script: $TRAVIS_BUILD_DIR/.github/scripts/on-push.sh 1 1

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/cb057279c430d91a47a8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always