include ../Makefile.conf

# Module name and description
MODULE_NAME = MONTE_CARLO_LOCALIZATION
MODULE_COMMENT = Monte Carlo Localization

SUBDIRS = monte_carlo_localization

LINK = g++

# Application specific include directories.
IFLAGS += 

# Required default libraries to comunicate with Carmen Core.
LFLAGS += 
CFLAGS += -Wall
# Source code files (.c, .cpp) 
SOURCES = 

# Public headers, linked to 'carmen/include/carmen/'.
PUBLIC_INCLUDES = 

# Public libraries, linked to 'carmen/lib'.
PUBLIC_LIBRARIES = 

# Public binaries, your application specific module laucher, copied to 'carmen/bin'.
PUBLIC_BINARIES = 

TARGETS = 
PUBLIC_LIBRARIES_SO =

# rules

include ../Makefile.rules

