include ../../Makefile.conf

CFLAGS += 
IFLAGS += 
LFLAGS += -lglobal -lipc -lparam_interface -llocalize_ackerman_interface -lbumblebee_basic_interface

MODULE_NAME = RDDF_PREDICT
MODULE_COMMENT = 

SOURCES = rddf_predict.c
PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES = 
PUBLIC_BINARIES = rddf_predict

TARGETS = rddf_predict

rddf_predict: rddf_predict.o 

include ../../Makefile.rules
