%YAML:1.0
---
aruco_bc_dict: ARUCO_MIP_36h12
aruco_bc_nmarkers: 6
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:1, corners:[ [ -4500., 750., 0. ], [ -3000., 750., 0. ], [
       -3000., -750., 0. ], [ -4500., -750., 0. ] ] }
   - { id:2, corners:[ [ -2700., 750., 0. ], [ -1200., 750., 0. ], [
       -1200., -750., 0. ], [ -2700., -750., 0. ] ] }
   - { id:3, corners:[ [ -900., 750., 0. ], [ 600., 750., 0. ], [ 600.,
       -750., 0. ], [ -900., -750., 0. ] ] }
   - { id:4, corners:[ [ 900., 750., 0. ], [ 2400., 750., 0. ], [ 2400.,
       -750., 0. ], [ 900., -750., 0. ] ] }
   - { id:5, corners:[ [ 2700., 750., 0. ], [ 4200., 750., 0. ], [ 4200.,
       -750., 0. ], [ 2700., -750., 0. ] ] }
   - { id:6, corners:[ [ 4500., 750., 0. ], [ 6000., 750., 0. ], [ 6000.,
       -750., 0. ], [ 4500., -750., 0. ] ] }
