include ../../Makefile.conf

LINK = g++

MODULE_NAME = HYPERGRAPHSCLAM MESSAGES
MODULE_COMMENT =

IFLAGS += -I$(CARMEN_HOME)/src/hypergraphsclam/Helpers/ -I$(CARMEN_HOME)/src/hypergraphsclam/Messages/

#cheating
IFLAGS += -std=c++11 -O2

include ../../Makefile.rules
