include ../../Makefile.conf

LINK = g++

MODULE_NAME = HyperGraphsclam Messages
MODULE_COMMENT =   

IFLAGS += -I$(CARMEN_HOME)/src/hypergraphsclam/Helpers/ -I$(CARMEN_HOME)/src/hypergraphsclam/Messages/

#cheating
IFLAGS += -std=c++11 -O0 -g

include ../../Makefile.rules
