include ../../Makefile.conf

CFLAGS += 
IFLAGS += 
LFLAGS += 

MODULE_NAME = SPLIT LOG
MODULE_COMMENT = Utility to split logs

SOURCES = util_split_log.cpp
PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES =  
PUBLIC_BINARIES = util_split_log

TARGETS = util_split_log

util_split_log: util_split_log.o

include ../../Makefile.rules
